FileVersion = 1
Dependencies = {corlib = "*", "Atma.Common" = "*", "Beef.Linq" = "*", "Atma.Entities" = "*"}

[Project]
Name = "BeefSand"
StartupObject = "BeefSand.Program"

[Configs.Release.Win64]
VectorizeLoops = true
